"""add session adapter field

Revision ID: 25f0e9e77fed
Revises: e57f25d5ec90
Create Date: 2026-02-04 18:20:00.041302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f0e9e77fed'
down_revision: Union[str, Sequence[str], None] = 'e57f25d5ec90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('adapter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('sessions') as batch_op:
        batch_op.drop_column('adapter')
